import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { HalfFloatType } from 'three';
import { WebGPURenderer } from 'three/webgpu';

const root = fileURLToPath(new URL('.', import.meta.url));
const repository = fileURLToPath(new URL('../../', import.meta.url));
const output = new URL('../../OEngine/src/shaders/atmosphere/lut.ts', import.meta.url);
const cache = new URL('./node_modules/.cache/eengine-atmosphere/', import.meta.url);
await mkdir(cache, { recursive: true });
const sources = JSON.parse(await readFile(new URL('./sources.json', import.meta.url), 'utf8'));
for (const file of sources.files) {
  const digest = createHash('sha256').update(await readFile(new URL(file.path, import.meta.url))).digest('hex');
  if (digest !== file.sha256) throw new Error(`Pinned upstream source changed: ${file.path}`);
}
await build({
  stdin: {
    contents: `export { AtmosphereLUTTexturesWebGPU } from './upstream/atmosphere/src/webgpu/AtmosphereLUTTexturesWebGPU.ts';
export { AtmosphereParameters } from './upstream/atmosphere/src/webgpu/AtmosphereParameters.ts';`,
    resolveDir: root, loader: 'ts'
  },
  outfile: fileURLToPath(new URL('source.mjs', cache)),
  alias: {
    '@takram/three-geospatial/webgpu': fileURLToPath(new URL('./compiler-support.ts', import.meta.url)),
    '@takram/three-geospatial': fileURLToPath(new URL('./compiler-support.ts', import.meta.url))
  },
  bundle: true, packages: 'external', format: 'esm', platform: 'node'
});
const { AtmosphereParameters, AtmosphereLUTTexturesWebGPU } = await import(new URL('source.mjs', cache));
// Only the offline node compiler is used. No adapter/device or network is accessed.
const compiler = new WebGPURenderer({ canvas: { width: 1, height: 1, style: {}, addEventListener() {} } });
const lut = new AtmosphereLUTTexturesWebGPU();
lut.setup(new AtmosphereParameters(), HalfFloatType);
const context = lut.createContext();
const stages = [];
const renderer = {
  hasFeature: () => false, hasCompatibility: () => false,
  backend: { compatibilityMode: false, utils: { getTextureSampleData: () => ({ primarySamples: 1 }) },
    device: { limits: { maxUniformBufferBindingSize: 65536 } } },
  compute(node, dispatch) {
    const builder = compiler.backend.createNodeBuilder(node, this);
    builder.build();
    const name = node.name.match(/\[(.+)\]/)[1];
    // Explicit f32 LOD. No algorithm, sample count, branch or reduction changes.
    const wgsl = builder.computeShader.replace(/(textureSampleLevel\([^\n]*), 0 \);/g, '$1, 0.0 );');
    const uniforms = builder.uniforms.compute.filter(u => u.type === 'mat3');
    for (const uniform of uniforms) {
      if (JSON.stringify(uniform.node.value.elements) !== '[1,0,0,0,1,0,0,0,1]') {
        throw new Error(`Unexpected LUT transform ${name}/${uniform.name}`);
      }
    }
    stages.push({ name, dispatch, identityMatrices: uniforms.length, wgsl });
  }
};
for (const method of ['computeTransmittance', 'computeMultipleScattering', 'computeScattering', 'computeIrradiance']) {
  lut[method](renderer, context);
}
for (const stage of stages) {
  const file = new URL(`${stage.name}.wgsl`, cache);
  await writeFile(file, stage.wgsl);
  const result = spawnSync(process.execPath, [fileURLToPath(new URL('./validate-wgsl.mjs', import.meta.url)), fileURLToPath(file)],
    { cwd: repository, encoding: 'utf8' });
  if (result.status !== 0) throw new Error(`${stage.name}: ${result.stderr}\n${result.stdout}`);
}
const text = `// Generated by tools/atmosphere-port/generate.mjs; DO NOT EDIT.\n` +
  `// Takram ${sources.revision}; notices: render/assets/takram/LICENSE-atmosphere.\n` +
  `// Fixed default Earth profile, combined Mie + separate higher-order scattering, rgba16float.\n` +
  `export const atmosphereLutStages = ${JSON.stringify(stages, null, 2)} as const;\n`;
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8') !== text) throw new Error('Atmosphere LUT output is stale');
} else {
  await mkdir(new URL('.', output), { recursive: true });
  await writeFile(output, text);
}
console.log(`${stages.length} pinned LUT stages: source hashes, WGSL validation and ${process.argv.includes('--check') ? 'reproduction' : 'generation'} passed`);
