// Registry of real-GPU oracles.
//
// Adding oracle #4 is one entry here plus its module; the CLI, the host page and
// the static server need no new code. Fields:
//   name         CLI selector
//   file         repository-relative path on disk (existence preflight + reports)
//   url          origin-relative URL the browser imports
//   entry        exported function called as entry(device)
//   allowPrefixes extra static-server prefixes this oracle additionally needs
//   note         provenance, or the exact observed blocker, shown in reports

export const oracles = Object.freeze([
  Object.freeze({
    name: "vsm-v4-r2",
    file: "OEngine/tests/oracle/vsm-v4-r2-gpu.mjs",
    url: "/OEngine/tests/oracle/vsm-v4-r2-gpu.mjs",
    entry: "runVsmR2GpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 8 },
    description:
      "Complete receiver demand, coarse guard capacity, same-epoch reclamation, empty completion, query states and abort retry.",
  }),
  Object.freeze({
    name: "fsr3-shading-pyramid",
    file: "OEngine/tests/oracle/fsr3-shading-pyramid-gpu.mjs",
    url: "/OEngine/tests/oracle/fsr3-shading-pyramid-gpu.mjs",
    entry: "runFsr3ShadingPyramidGpuOracle",
    requiredFeatures: ["texture-formats-tier1"],
    description:
      "Production parallel source lanes against frozen serial SDK math: NPOT, jitter, motion, exposure and f32/f16 products.",
  }),
  Object.freeze({
    name: "native-raster-triangle-count",
    file: "OEngine/tests/oracle/native-raster-triangle-count-gpu.mjs",
    url: "/OEngine/tests/oracle/native-raster-triangle-count-gpu.mjs",
    entry: "runNativeRasterTriangleCountGpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 7 },
    description:
      "Production triangle bucket edges and sides, complete capacity-miss and stale-directory work.",
  }),
  Object.freeze({
    name: "fsr3-luma-pyramid",
    file: "OEngine/tests/oracle/fsr3-luma-pyramid-gpu.mjs",
    url: "/OEngine/tests/oracle/fsr3-luma-pyramid-gpu.mjs",
    entry: "runFsr3LumaPyramidGpuOracle",
    requiredFeatures: ["texture-formats-tier1"],
    description:
      "Production local multi-mip reduction against a CPU f32 NPOT reference and frozen per-mip GPU fp16/depth/exposure expectations.",
  }),
  Object.freeze({
    name: "temporal-input-contract",
    file: "OEngine/tests/oracle/temporal-input-contract-gpu.mjs",
    url: "/OEngine/tests/oracle/temporal-input-contract-gpu.mjs",
    entry: "runTemporalInputContractGpuOracle",
    requiredLimits: { maxStorageTexturesPerShaderStage: 3 },
    description:
      "Production identity/coverage/jittered motion and shared conservative LOD anchor numeric contract.",
  }),
  Object.freeze({
    name: "pc-texture-residency",
    file: "OEngine/tests/oracle/pc-texture-residency-gpu.mjs",
    url: "/OEngine/tests/oracle/pc-texture-residency-gpu.mjs",
    entry: "runPcTextureResidencyGpuOracle",
    requiredFeatures: ["texture-compression-bc"],
    requiredLimits: { maxSampledTexturesPerShaderStage: 19, maxStorageBuffersPerShaderStage: 10 },
    description:
      "T4.2 sole BC Residency, NPOT/R8/scalar routes, actual native sampling, abort/promotion/fenced zero.",
    timeoutMs: 120000,
  }),
  Object.freeze({
    name: "texture-renderer",
    file: "OEngine/tests/oracle/texture-renderer-gpu.mjs",
    url: "/OEngine/tests/oracle/texture-renderer-gpu.mjs",
    entry: "runTextureRendererGpuOracle",
    allowPrefixes: [
      "examples/assets/three/rendering-lab/dungeon_warkarma.glb",
      "OEngine/src/render/assets/",
      "OEngine/src/assets/web-cook/wasm/vendor/",
    ],
    description: "Complete small authored dungeon Renderer, original 25 textures, 1080p.",
    timeoutMs: 1800000,
  }),
  Object.freeze({
    name: "pc-texture-recovery",
    file: "OEngine/tests/oracle/pc-texture-product-gpu.mjs",
    url: "/OEngine/tests/oracle/pc-texture-product-gpu.mjs",
    entry: "runPcTextureRecoveryGpuOracle",
    requiredFeatures: ["texture-compression-bc", "float32-filterable"],
    description:
      "T4.1 affected replay validation: controlled device destroy, fresh adapter, disk Product and exact coverage/native sampling.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "pc-texture-import",
    file: "OEngine/tests/oracle/pc-texture-import-gpu.mjs",
    url: "/OEngine/tests/oracle/pc-texture-import-gpu.mjs",
    entry: "runPcTextureImportGpuOracle",
    requiredFeatures: ["texture-compression-bc"],
    description:
      "T4.1 real browser KTX Worker, ETC1S/UASTC/Zstd, full mips, compressed array decode and failed-import retry.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "pc-texture-product",
    file: "OEngine/tests/oracle/pc-texture-product-gpu.mjs",
    url: "/OEngine/tests/oracle/pc-texture-product-gpu.mjs",
    entry: "runPcTextureProductGpuOracle",
    requiredFeatures: ["texture-compression-bc", "float32-filterable"],
    description:
      "T4.1 non-production BC product/full mips/NPOT/native evaluator/coverage/Worker and new-device replay.",
    timeoutMs: 1800000,
  }),
  Object.freeze({
    name: "texture-encoder-probe",
    file: "OEngine/tests/oracle/texture-encoder-probe-gpu.mjs",
    url: "/OEngine/tests/oracle/texture-encoder-probe-gpu.mjs",
    entry: "runTextureEncoderProbeGpuOracle",
    requiredFeatures: ["texture-compression-bc", "timestamp-query"],
    allowPrefixes: [".local/texture-design-spark/src/"],
    description:
      "T4.0 isolated pinned external Spark 1K/2K/4K encode cost/quality/output ownership probe; never a production owner.",
    timeoutMs: 300000,
  }),
  Object.freeze({
    name: "lighting-product-inspection",
    file: "OEngine/tests/oracle/lighting-product-inspection-gpu.mjs",
    url: "/OEngine/tests/oracle/lighting-product-inspection-gpu.mjs",
    entry: "runLightingProductInspectionGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredFeatures: ["timestamp-query"],
    description: "Untimed real GPU occupancy, compact ranges and list-length accounting for L3.3.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "lighting-dynamics",
    file: "OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    entry: "runLightingDynamicsGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredFeatures: ["timestamp-query"],
    description: "Targeted retained light parameter updates, add/remove/reorder and independent colored HDR.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "lighting-acceptance",
    file: "OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    entry: "runLightingAcceptanceGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredFeatures: ["timestamp-query"],
    description:
      "L3.3 same-workload production local light matrix, low coverage, dynamic publication and independent HDR.",
    timeoutMs: 1800000,
  }),
  Object.freeze({
    name: "local-light-integration",
    file: "OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    entry: "runLocalLightIntegrationGpuOracle",
    requiredFeatures: ["texture-compression-bc", "texture-formats-tier1"],
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    description:
      "Native light ABI with all material routes/two binding sets/alpha/Sun/VSM/AO/Temporal/FSR and resource-limit continuation.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "local-light-epochs",
    file: "OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    entry: "runLocalLightEpochGpuOracle",
    requiredFeatures: ["texture-compression-bc", "texture-formats-tier1"],
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    description: "Local-light old epoch teardown, rejection and complete new device reconstruction.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "local-light-native",
    file: "OEngine/tests/oracle/local-light-native-gpu.mjs",
    url: "/OEngine/tests/oracle/local-light-native-gpu.mjs",
    entry: "runLocalLightNativeGpuOracle",
    requiredFeatures: ["timestamp-query"],
    allowPrefixes: ["OEngine/src/render/assets/"],
    description:
      "L3.2 sole production generator/product/native consumer on real winner/material/Sun/VSM/IBL/AO/Temporal providers.",
    timeoutMs: 240000,
  }),
  Object.freeze({
    name: "local-light-cost",
    file: "OEngine/tests/oracle/local-light-native-gpu.mjs",
    url: "/OEngine/tests/oracle/local-light-native-gpu.mjs",
    entry: "runLocalLightCostGpuOracle",
    requiredFeatures: ["timestamp-query"],
    allowPrefixes: ["OEngine/src/render/assets/"],
    description: "L3.1 alternating same-work DIRECT/SPARSE generator+native Surface 1080p cost.",
    timeoutMs: 900000,
  }),
  Object.freeze({
    name: "local-light-work",
    file: "OEngine/tests/oracle/local-light-work-gpu.mjs",
    url: "/OEngine/tests/oracle/local-light-work-gpu.mjs",
    entry: "runLocalLightWorkGpuOracle",
    description:
      "L3.1 isolated local-light count/scan/scatter, complete overflow, staged DB abort/retry and independent support coverage.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "lighting-support",
    file: "OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    entry: "runLightingSupportGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredFeatures: ["timestamp-query"],
    description:
      "L3.0 actual production HDR support at finite-radius, offscreen, unbounded, huge Spot and near crossings.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "lighting-low-coverage",
    file: "OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    entry: "runLightingLowCoverageGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredFeatures: ["timestamp-query"],
    description:
      "L3.0 same 1080p production scene/material/quality at far camera, 0/1/4/8/16/32 raw 120-frame baseline.",
    timeoutMs: 240000,
  }),
  Object.freeze({
    name: "lighting-baseline",
    file: "OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    entry: "runLightingBaselineGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredFeatures: ["timestamp-query"],
    description:
      "L3.0 unchanged production Lighting, 1080p, 0..1024 Point/Spot/mixed sparse/overlap, independent HDR and raw timestamps.",
    timeoutMs: 900000,
  }),
  Object.freeze({
    name: "lighting-boundaries",
    file: "OEngine/tests/oracle/lighting-boundaries-gpu.mjs",
    url: "/OEngine/tests/oracle/lighting-boundaries-gpu.mjs",
    entry: "runLightingBoundariesGpuOracle",
    description: "L3.0 independent boundary expectations evaluated by actual LightDatabase WGSL helpers.",
    timeoutMs: 120000,
  }),
  Object.freeze({
    name: "geometry-shadow-view",
    file: "OEngine/tests/oracle/geometry-shadow-view-gpu.mjs",
    url: "/OEngine/tests/oracle/geometry-shadow-view-gpu.mjs",
    entry: "runGeometryShadowViewGpuOracle",
    requiredFeatures: ["timestamp-query"],
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    description:
      "Actual Renderer off-camera caster, native alpha, visible receiver HDR and shadow abort/retry.",
    timeoutMs: 180_000,
  }),
  Object.freeze({
    name: "geometry-budgeted-residency",
    file: "OEngine/tests/oracle/geometry-budgeted-residency-gpu.mjs",
    url: "/OEngine/tests/oracle/geometry-budgeted-residency-gpu.mjs",
    entry: "runGeometryBudgetedResidencyGpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 16, maxStorageBufferBindingSize: 268435456 },
    description:
      "Budget/profile boundary bank accesses, true pressure, pinned coarse coverage and fair delayed uploads.",
    timeoutMs: 180_000,
  }),
  Object.freeze({
    name: "native-surface-multi-product-production",
    file: "OEngine/tests/oracle/native-surface-production-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-production-gpu.mjs",
    entry: "runNativeSurfaceMultiProductProductionGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/", "OEngine/src/assets/web-cook/wasm/vendor/"],
    requiredFeatures: ["texture-formats-tier1"],
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    description:
      "Actual Renderer with two same-revision Products, abort/retry, alpha/Temporal and all-source device recovery.",
    timeoutMs: 240_000,
  }),
  Object.freeze({
    name: "native-surface-acceptance",
    file: "OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-acceptance-gpu.mjs",
    entry: "runNativeSurfaceAcceptanceGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredFeatures: ["timestamp-query"],
    description:
      "S3 actual Renderer 1080p high coverage Standard/coat/custom/Unlit, 4/8/32 lights and 1/8/32 native programs, HDR oracle and timings.",
    note: "Generated scene complements authored Showcase image acceptance; renderer negotiates its own complete device profile.",
    timeoutMs: 600000,
  }),
  Object.freeze({
    name: "native-surface-product-production",
    file: "OEngine/tests/oracle/native-surface-production-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-production-gpu.mjs",
    entry: "runNativeSurfaceProductProductionGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/", "OEngine/src/assets/web-cook/wasm/vendor/"],
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    requiredFeatures: ["texture-formats-tier1"],
    description:
      "S2 actual ordinary Scene WASM Product admission, native Visibility/VSM/Surface/Temporal/recovery closure.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "native-surface-production",
    file: "OEngine/tests/oracle/native-surface-production-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-production-gpu.mjs",
    entry: "runNativeSurfaceProductionGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    requiredFeatures: ["texture-formats-tier1"],
    description:
      "S2 actual Renderer ownership, native instance publication, winner/HDR/Temporal/FSR, update/abort/retry/resize.",
    note: "Renderer negotiates its own device; oracle captures errors on that real production device. This is a correctness closure, not S3 performance acceptance.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "native-surface-resource-profile",
    file: "OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    entry: "runNativeSurfaceResourceProfileGpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    requiredFeatures: ["texture-compression-bc", "texture-formats-tier1"],
    description:
      "S1 complete Product-geometry resource profile, native sunlight and resident winner input; not VG scene acceptance.",
    timeoutMs: 120000,
  }),
  Object.freeze({
    name: "native-surface-device-epoch",
    file: "OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    entry: "runNativeSurfaceDeviceEpochGpuOracle",
    description:
      "S1 controlled device destruction and native subsystem reconstruction on two independent device epochs.",
    timeoutMs: 120000,
  }),
  Object.freeze({
    name: "native-surface-cost",
    file: "OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    entry: "runNativeSurfaceCostGpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    requiredFeatures: ["texture-compression-bc", "texture-formats-tier1", "timestamp-query"],
    description: "S1 isolated 1080p native multi-route/Temporal/FSR cost; not production acceptance.",
    timeoutMs: 180000,
  }),
  Object.freeze({
    name: "native-surface-perspective",
    file: "OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    entry: "runNativeSurfacePerspectiveGpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    requiredFeatures: ["texture-compression-bc", "texture-formats-tier1"],
    description: "S1 perspective reconstruction, physical sun math and real GPU exposure update.",
    timeoutMs: 120000,
  }),
  Object.freeze({
    name: "native-execution-bins",
    file: "OEngine/tests/oracle/native-execution-bins-gpu.mjs",
    url: "/OEngine/tests/oracle/native-execution-bins-gpu.mjs",
    entry: "runNativeExecutionBinsGpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    description: "S1 native pixel execution bins, complete tails, capacity and unique-writer coverage.",
    timeoutMs: 60000,
  }),
  Object.freeze({
    name: "native-surface-integration",
    file: "OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    url: "/OEngine/tests/oracle/native-surface-integration-gpu.mjs",
    entry: "runNativeSurfaceIntegrationGpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    requiredFeatures: ["texture-compression-bc", "texture-formats-tier1"],
    description: "S1 isolated native winner/material/HDR/Temporal/FSR chain; no production cutover.",
    timeoutMs: 120000,
  }),
  Object.freeze({
    name: "native-material",
    file: "OEngine/tests/oracle/native-material-gpu.mjs",
    url: "/OEngine/tests/oracle/native-material-gpu.mjs",
    entry: "runNativeMaterialGpuOracle",
    requiredFeatures: ["texture-compression-bc"],
    description:
      "S1 native Standard/Coat/Unlit/custom graph, explicit gradients and immutable publication transactions.",
    timeoutMs: 60000,
    note: "Component only: fixture geometry inputs and linear textures; no production cutover or S1 closure claim.",
  }),
  Object.freeze({
    name: "framegraph-lifecycle",
    file: "OEngine/tests/oracle/framegraph-lifecycle-gpu.mjs",
    url: "/OEngine/tests/oracle/framegraph-lifecycle-gpu.mjs",
    entry: "runFrameGraphLifecycleGpuOracle",
    requiredFeatures: ["timestamp-query"],
    description:
      "A0/A1 production compiled executor, pooled/native lifetime, resize binding and diagnostics WGSL.",
    timeoutMs: 60000,
    note: "Real GPU component chain with independent buffer/diagnostic assertions.",
  }),
  Object.freeze({
    name: "frame-timing",
    file: "OEngine/tests/oracle/frame-timing-gpu.mjs",
    url: "/OEngine/tests/oracle/frame-timing-gpu.mjs",
    entry: "runFrameTimingGpuOracle",
    requiredFeatures: ["timestamp-query"],
    description: "A0 persistent timer modes, query/marker tax and real GPU span/result assertions.",
    timeoutMs: 60000,
    note: "Production timer components, not a full-frame benchmark.",
  }),
  Object.freeze({
    name: "environment-probe",
    file: "tools/gpu-oracle/self-test/environment-probe.mjs",
    url: "/__gpu-oracle/self-test/environment-probe.mjs",
    entry: "runEnvironmentProbe",
    description:
      "Minimal real-GPU smoke test: one compute dispatch, storage-buffer readback, asserted on the CPU.",
    timeoutMs: 60_000,
    note: "Run this first on a new machine or CI runner; it separates harness/driver availability from oracle logic.",
  }),
  Object.freeze({
    name: "hzb-conservative",
    file: "OEngine/tests/oracle/hzb-conservative-gpu.mjs",
    url: "/OEngine/tests/oracle/hzb-conservative-gpu.mjs",
    entry: "runConservativeHzbGpuOracle",
    requiredFeatures: ["texture-formats-tier1"],
    description:
      "Exhaustive rg16float half-boundary reduction plus all 1296 HZB footprint rectangles against buildHzbReference.",
    timeoutMs: 180_000,
    note: "Independent CPU reference; strongest numeric oracle in the repository.",
  }),
  Object.freeze({
    name: "virtual-geometry-handoff",
    file: "OEngine/tests/oracle/virtual-geometry-handoff-gpu.mjs",
    url: "/OEngine/tests/oracle/virtual-geometry-handoff-gpu.mjs",
    entry: "runVirtualGeometryHandoffGpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    description:
      "VirtualGeometryMeshletWorkCandidate queue/draw-indirect handoff with exact compacted cluster IDs.",
    timeoutMs: 180_000,
    note: "Drives the production owner VirtualGeometryMeshletWorkCandidate from OEngine/.test-dist.",
  }),
  Object.freeze({
    name: "geometry-product-scale",
    file: "OEngine/tests/oracle/geometry-product-scale-gpu.mjs",
    url: "/OEngine/tests/oracle/geometry-product-scale-gpu.mjs",
    entry: "runGeometryProductScaleGpuOracle",
    requiredFeatures: ["timestamp-query"],
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    description:
      "Product publication, depth-0/deep forests, instance multiplicity, multi-Product and fail-closed work/abort controls.",
    timeoutMs: 180_000,
    note: "Uses production MultiRuntime, HierarchicalWorkGenerator and MeshletWorkCandidate; no alternative renderer.",
  }),
  Object.freeze({
    name: "geometry-scale-production",
    file: "OEngine/tests/oracle/geometry-scale-production-gpu.mjs",
    url: "/OEngine/tests/oracle/geometry-scale-production-gpu.mjs",
    entry: "runGeometryScaleProductionGpuOracle",
    allowPrefixes: ["OEngine/src/render/assets/"],
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    requiredFeatures: ["texture-formats-tier1", "timestamp-query"],
    timeoutMs: 300000,
    description:
      "Actual Renderer 1080p exhaustive raster/winner coverage for 10k/100k procedural instances and 8/66 Products.",
    note: "Resident position-only Unlit scale fixture, not authored material/streaming quality or historical speedup.",
  }),
  Object.freeze({
    name: "virtual-geometry-instance-culling",
    file: "OEngine/tests/oracle/virtual-geometry-instance-culling-gpu.mjs",
    url: "/OEngine/tests/oracle/virtual-geometry-instance-culling-gpu.mjs",
    entry: "runVirtualGeometryInstanceCullingGpuOracle",
    requiredLimits: { maxStorageBuffersPerShaderStage: 16 },
    description:
      "HierarchicalWorkGenerator root/hierarchy kernels over 20 camera frames, with the old double-transform false rejection as negative control.",
    timeoutMs: 180_000,
    note: "Drives the production owner HierarchicalWorkGenerator from OEngine/.test-dist.",
  }),
  Object.freeze({
    name: "self-test-wrong-kernel",
    file: "tools/gpu-oracle/self-test/hzb-conservative-wrong-kernel.mjs",
    url: "/__gpu-oracle/self-test/hzb-conservative-wrong-kernel.mjs",
    entry: "runWrongKernelHzbOracle",
    requiredFeatures: ["texture-formats-tier1"],
    description:
      "Negative control: the HZB reduction oracle with a deliberately non-conservative GPU kernel.",
    timeoutMs: 180_000,
    negativeControl: true,
    note: "Must FAIL. Proves the harness propagates failures produced by real GPU output. Never a production oracle.",
  }),
]);

export function findOracle(name) {
  return oracles.find((oracle) => oracle.name === name) ?? null;
}
