/**
 * automatic_exposure：定义对应渲染阶段使用的 WGSL 着色器代码。
 */


export {
  EXPOSURE_ADAPT_LEGACY_COMPUTE_WGSL as EXPOSURE_ADAPT_WGSL,
  EXPOSURE_HISTOGRAM_LEGACY_COMPUTE_WGSL as EXPOSURE_HISTOGRAM_WGSL,
  EXPOSURE_REDUCE_LEGACY_COMPUTE_WGSL as EXPOSURE_REDUCE_WGSL
} from "./temporal_post_legacy.generated.js";

export const EXPOSURE_HISTOGRAM_BIN_COUNT = 128;
export const EXPOSURE_HISTOGRAM_BUFFER_SIZE = EXPOSURE_HISTOGRAM_BIN_COUNT * 4;
export const EXPOSURE_VALUE_BUFFER_SIZE = 4;
export const EXPOSURE_SETTINGS_BUFFER_SIZE = 20;
