/**
 * bloom：定义对应渲染阶段使用的 WGSL 着色器代码。
 */

export {
  BLOOM_COMPOSITE_LEGACY_FRAGMENT_WGSL as BLOOM_COMPOSITE_WGSL,
  BLOOM_DOWNSAMPLE_LEGACY_FRAGMENT_WGSL as BLOOM_DOWNSAMPLE_WGSL,
  BLOOM_PREFILTER_LEGACY_FRAGMENT_WGSL as BLOOM_PREFILTER_WGSL,
  BLOOM_UPSAMPLE_LEGACY_FRAGMENT_WGSL as BLOOM_UPSAMPLE_WGSL,
  TEMPORAL_POST_VERTEX_WGSL as BLOOM_VERTEX_WGSL
} from "./temporal_post_legacy.generated.js";

export const BLOOM_FORMAT = "rgba16float" as const;
export const BLOOM_MIP_COUNT = 5;
export const BLOOM_UPSAMPLE_FACTOR = 0.85;
