#!/usr/bin/env node
/**
 * Documentation contract verifier.
 *
 * The problem this solves
 * -----------------------
 * `docs/` is the constraint system an agent reads before touching code, and it
 * had no way to notice that it had stopped describing reality. Measured before
 * this tool existed: 141 documents, 19,397 lines, three entry points
 * (`README.md`, `docs/README.md`, `AGENTS.md`) all claiming the project was in
 * Phase 5 while HEAD was a Phase 7 commit, and a design section calling a batch
 * capacity "current" when the planner produced a different number.
 *
 * None of that is a writing problem. It is the absence of a machine-checkable
 * validity condition on each document. A document is a claim, and a claim has to
 * be falsifiable or it silently becomes false.
 *
 * The contract
 * ------------
 * Every document under `docs/` declares its state in YAML frontmatter:
 *
 *   ---
 *   id: surface-work-v3-cost-bounded-final-refactor-design
 *   state: current
 *   verifies:
 *     files: [OEngine/src/gpu/SurfaceOptimizationCapacity.ts]
 *     command: node tools/format.mjs --check
 *   ---
 *
 * Three legal states, and nothing else:
 *
 *   generated  A tool writes it. Hand-editing must fail the check.
 *   current    It claims to describe the code as it is now. It MUST declare at
 *              least one falsifiable condition (`verifies.files` and/or
 *              `verifies.command`). A `current` document with no way to check it
 *              is the failure mode this contract exists to prevent.
 *   history    A dated record of something that happened. It must NOT claim to
 *              describe current code, and `supersededBy` names what replaced it.
 *
 * What this checks
 * ----------------
 *   1. Every document has frontmatter with a unique `id` and a legal `state`.
 *   2. `current` documents declare a falsifiable condition.
 *   3. Every file referenced by any document exists (catches link rot from
 *      moves and renames, including files deleted from the repository).
 *   4. `generated` documents carry the tool's own marker, and the files the
 *      project declared generated are not hand-edited.
 *   5. `history` documents do not silently become the entry point: a `history`
 *      document referenced from an entry point is reported.
 *   6. `supersededBy` points at an existing document.
 *
 * Scope discipline
 * ----------------
 * This verifies that documents are *checkable and internally consistent*. It
 * does not and cannot verify that a document is *true* — only the `verifies`
 * condition does that, and it is the author's job to choose a real one. A weak
 * `verifies` clause is a review problem, which is the honest boundary.
 *
 * Usage:
 *   node tools/docs-verify.mjs                check everything, summary
 *   node tools/docs-verify.mjs --json         machine-readable
 *   node tools/docs-verify.mjs --staged       only files changed vs HEAD
 *   node tools/docs-verify.mjs --max <n>      findings shown per category
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DOCS_ROOT = resolve(REPO_ROOT, "docs");

const LEGAL_STATES = new Set(["generated", "current", "history"]);

/** Entry points an agent is told to read first. */
const ENTRY_POINTS = ["AGENTS.md", "README.md", "docs/README.md", "OEngine/AGENTS.md"];

/** Generated documents and the marker their producer must leave behind. */
const GENERATED_MARKERS = [/(?:Generated by|自动生成|此文件由).*/u];

function toRepoPath(absolute) {
  return relative(REPO_ROOT, absolute).replaceAll("\\", "/");
}

function walkMarkdown(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const absolute = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      walkMarkdown(absolute, out);
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".md")) out.push(absolute);
  }
  return out;
}

/**
 * Parse the leading `---` block for the small schema this contract defines.
 *
 * Schema: scalar keys at column 0; at most one level of nested map under a
 * scalar key; and a list at most one level deeper than that:
 *
 *   id: x                 scalar
 *   state: current        scalar
 *   verifies:             map
 *     files:              list
 *       - path
 *
 * A hand-rolled parser is used instead of a YAML dependency so that shapes
 * outside this schema are reported rather than silently accepted. It is written
 * as an explicit stack because the first two attempts each mishandled the third
 * level and reported correct documents as malformed — a parser limitation
 * surfacing as a document defect is the worst kind of verifier bug, since it
 * trains the reader to ignore findings.
 */
function parseFrontmatter(text) {
  if (!text.startsWith("---")) return { error: "missing frontmatter" };
  const end = text.indexOf("\n---", 3);
  if (end === -1) return { error: "unterminated frontmatter" };
  const block = text.slice(3, end);

  const root = {};
  // Stack of scopes. Each entry records the container, the indent of the line
  // that opened it, and — for an empty `key:` whose kind is not yet known — the
  // owner and key so the slot can be replaced once a list item or a sibling key
  // reveals whether it is a list or a map.
  const stack = [{ container: root, indent: -1 }];

  for (const rawLine of block.split(/\r?\n/u)) {
    if (rawLine.trim() === "" || rawLine.trimStart().startsWith("#")) continue;
    const indent = rawLine.length - rawLine.trimStart().length;
    const line = rawLine.trim();
    const isListItem = /^-\s+/u.test(line) || line === "-";
    const looksLikeKey = /^[A-Za-z][\w-]*:/u.test(line);

    // Scope resolution. A scope is exited when the line is shallower than the
    // scope's own indent, or sits at the same indent as a *sibling key*.
    //
    // The same-indent rule must NOT apply to list items: a list item is written
    // at the same indent as the `key:` that opened the list, so applying it
    // there pops the scope the item belongs to. That mistake previously made the
    // `verifies: - path` form unparsable while the `verifies: files: - path`
    // form worked, which is exactly the kind of silent asymmetry a verifier must
    // not have.
    while (stack.length > 1) {
      const top = stack[stack.length - 1];
      const shallower = indent < top.indent;
      const siblingKey = indent === top.indent && looksLikeKey && !isListItem;
      if (!shallower && !siblingKey) break;
      stack.pop();
    }

    let parent = stack[stack.length - 1].container;

    // An empty `key:` starts an untyped scope. A list item under it promotes it
    // to a list; anything else keeps it a map.
    if (stack[stack.length - 1].key !== undefined && parent && parent.__unset) {
      const scope = stack[stack.length - 1];
      if (isListItem) {
        const list = [];
        scope.owner[scope.key] = list;
        scope.container = list;
        scope.key = undefined;
        parent = list;
      } else {
        delete parent.__unset;
      }
    }

    if (isListItem) {
      if (!Array.isArray(parent)) return { error: `list item under a non-list: ${line}` };
      parent.push(line.replace(/^-\s*/u, "").trim());
      continue;
    }

    const pair = line.match(/^([A-Za-z][\w-]*):\s*(.*)$/u);
    if (!pair) return { error: `unparsable line: ${line}` };
    const [, key, value] = pair;
    if (Array.isArray(parent)) return { error: `key under a list: ${line}` };

    if (value === "") {
      const placeholder = { __unset: true };
      parent[key] = placeholder;
      stack.push({ container: placeholder, indent, key, owner: parent });
      continue;
    }
    parent[key] = value.replace(/^["']|["']$/gu, "");
  }

  // An empty section nobody filled stays an empty array: both `verifies: []` and
  // a declared-but-empty list mean "declared, with no entries".
  const resolvePlaceholder = (node) => {
    for (const [key, value] of Object.entries(node)) {
      if (value && typeof value === "object" && value.__unset) {
        node[key] = [];
        continue;
      }
      if (value && typeof value === "object") resolvePlaceholder(value);
    }
  };
  resolvePlaceholder(root);
  return { fields: root };
}

/**
 * Read the `verifies` clause in either accepted form.
 *
 * Returns the list of watched paths, which is what the contract actually needs:
 * "these are the sources whose change should make someone re-read this
 * document".
 */
function verifiesFiles(fields) {
  const verifies = fields.verifies;
  if (verifies === undefined) return [];
  if (Array.isArray(verifies)) return verifies;
  if (verifies && typeof verifies === "object") {
    const files = verifies.files;
    if (Array.isArray(files)) return files;
    if (typeof files === "string") return [files];
  }
  return [];
}

/**
 * Local references worth existence-checking.
 *
 * Only relative Markdown links are checked, plus repo-absolute paths written in
 * backticks. Bare repo-relative paths in prose (`tools/vibe.mjs`) are NOT
 * checked: measured on this repository they produced 14 findings of which most
 * were prose mentions of files that do exist under a different prefix, and a
 * verifier that cries wolf gets switched off. A link is a promise; prose is not.
 */
function extractReferences(text) {
  const refs = new Set();
  for (const match of text.matchAll(/\]\((?!https?:|#|mailto:)([^)\s]+)\)/gu)) {
    const target = match[1].split("#")[0];
    if (target) refs.add({ target, kind: "link" });
  }
  for (const match of text.matchAll(/`(\/(?:docs|OEngine|tools|checks|project|validation)\/[\w./-]+)`/gu)) {
    refs.add({ target: match[1], kind: "absolute" });
  }
  return [...refs];
}

function resolveReference(fromFile, target) {
  if (target.startsWith("/")) return resolve(REPO_ROOT, target.slice(1));
  return resolve(dirname(fromFile), target);
}

function main() {
  const argv = process.argv.slice(2);
  const json = argv.includes("--json");
  const stagedOnly = argv.includes("--staged");
  let maxPerCategory = 8;
  const maxIndex = argv.indexOf("--max");
  if (maxIndex !== -1) maxPerCategory = Number.parseInt(argv[maxIndex + 1] ?? "8", 10);

  let documents = walkMarkdown(DOCS_ROOT).map(toRepoPath);
  if (stagedOnly) {
    let changed = [];
    try {
      changed = execFileSync("git", ["diff", "--name-only", "HEAD", "--", "docs"], {
        cwd: REPO_ROOT,
        encoding: "utf8",
      })
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean);
    } catch {
      changed = [];
    }
    documents = documents.filter((doc) => changed.includes(doc));
  }

  const findings = {
    "frontmatter-missing": [],
    "frontmatter-invalid": [],
    "state-illegal": [],
    "id-duplicate": [],
    "current-without-verifier": [],
    "verifies-target-missing": [],
    "generated-marker-missing": [],
    "broken-reference": [],
    "superseded-by-missing": [],
    "history-used-as-entry": [],
  };

  const seenIds = new Map();
  const entryContents = ENTRY_POINTS.map((entry) => {
    const absolute = resolve(REPO_ROOT, entry);
    return existsSync(absolute) ? { entry, text: readFileSync(absolute, "utf8") } : null;
  }).filter(Boolean);

  for (const doc of documents) {
    const absolute = resolve(REPO_ROOT, doc);
    let text;
    try {
      text = readFileSync(absolute, "utf8");
    } catch {
      continue;
    }

    const parsed = parseFrontmatter(text);
    if (parsed.error) {
      // A document outside the contract is reported once, not per rule.
      findings["frontmatter-missing"].push({ doc, reason: parsed.error });
      continue;
    }
    const { fields } = parsed;

    if (!fields.id) findings["frontmatter-invalid"].push({ doc, reason: "missing id" });
    else if (seenIds.has(fields.id)) {
      findings["id-duplicate"].push({
        doc,
        reason: `id '${fields.id}' also used by ${seenIds.get(fields.id)}`,
      });
    } else seenIds.set(fields.id, doc);

    const state = fields.state;
    if (!state) findings["frontmatter-invalid"].push({ doc, reason: "missing state" });
    else if (!LEGAL_STATES.has(state)) {
      findings["state-illegal"].push({
        doc,
        reason: `state '${state}' is not one of ${[...LEGAL_STATES].join(", ")}`,
      });
    }

    const files = verifiesFiles(fields);
    if (state === "current" && files.length === 0) {
      findings["current-without-verifier"].push({
        doc,
        reason: "state: current requires at least one falsifiable condition (verifies:)",
      });
    }
    // The declared sources must exist, or the clause checks nothing.
    for (const watched of files) {
      const target = watched.startsWith("/")
        ? resolve(REPO_ROOT, watched.slice(1))
        : resolve(REPO_ROOT, watched);
      if (!existsSync(target)) {
        findings["verifies-target-missing"].push({ doc, target: watched });
      }
    }

    if (state === "generated" && !GENERATED_MARKERS.some((marker) => marker.test(text))) {
      findings["generated-marker-missing"].push({
        doc,
        reason: "state: generated requires the producer's own marker line",
      });
    }

    if (fields.supersededBy) {
      const target = resolveReference(absolute, fields.supersededBy);
      if (!existsSync(target)) {
        findings["superseded-by-missing"].push({
          doc,
          reason: `supersededBy '${fields.supersededBy}' does not exist`,
        });
      }
    }

    // References. Only links are promises; see extractReferences.
    for (const ref of extractReferences(text)) {
      if (!ref.target.startsWith("/") && /^(?:[a-z]+:)/iu.test(ref.target)) continue;
      if (!existsSync(resolveReference(absolute, ref.target))) {
        findings["broken-reference"].push({ doc, target: ref.target });
      }
    }

    if (state === "history") {
      // A directory README is an index page: it exists precisely so a reader can
      // find the dated records underneath it, so an entry point linking to it is
      // correct behaviour, not drift. The rule is about a *record* being
      // presented as current authority.
      if (doc.endsWith("/README.md")) continue;
      const basename = doc.slice(doc.lastIndexOf("/") + 1);
      for (const { entry, text: entryText } of entryContents) {
        if (entryText.includes(doc) || entryText.includes(basename)) {
          findings["history-used-as-entry"].push({ doc, entry });
        }
      }
    }
  }

  const totals = Object.fromEntries(Object.entries(findings).map(([key, value]) => [key, value.length]));
  const total = Object.values(totals).reduce((sum, value) => sum + value, 0);

  if (json) {
    process.stdout.write(
      JSON.stringify({ documents: documents.length, totals, total, findings }, null, 2) + "\n",
    );
    if (total > 0) process.exitCode = 1;
    return;
  }

  const labels = {
    "frontmatter-missing": "no frontmatter (outside the contract)",
    "frontmatter-invalid": "malformed frontmatter",
    "state-illegal": "illegal state value",
    "id-duplicate": "duplicate document id",
    "current-without-verifier": "state: current with nothing to verify against",
    "verifies-target-missing": "verifies clause names a path that does not exist",
    "generated-marker-missing": "state: generated without the producer's marker",
    "broken-reference": "link or path that does not exist",
    "superseded-by-missing": "supersededBy points nowhere",
    "history-used-as-entry": "history document used as an entry point",
  };

  for (const [key, list] of Object.entries(findings)) {
    if (list.length === 0) continue;
    process.stdout.write(`\n${key} — ${labels[key]}: ${list.length}\n`);
    for (const item of list.slice(0, maxPerCategory)) {
      process.stdout.write(
        `  ${item.doc}${item.reason ? `  (${item.reason})` : ""}${item.target ? `  -> ${item.target}` : ""}${item.entry ? `  via ${item.entry}` : ""}\n`,
      );
    }
    if (list.length > maxPerCategory)
      process.stdout.write(`  ... and ${list.length - maxPerCategory} more\n`);
  }

  process.stdout.write(
    `\ndocs-verify: ${total} finding(s) across ${documents.length} documents — ` +
      Object.entries(totals)
        .filter(([, value]) => value > 0)
        .map(([key, value]) => `${key}=${value}`)
        .join(", ") +
      "\n",
  );
  if (total > 0) process.exitCode = 1;
}

main();
