import { mkdir, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { discoverExamples } from "./discover-examples.mjs";

const scriptsDirectory = fileURLToPath(new URL(".", import.meta.url));
const examplesRoot = resolve(scriptsDirectory, "..");
const outputDirectory = resolve(examplesRoot, "stories", "generated");
const examples = await discoverExamples(examplesRoot);

await rm(outputDirectory, { recursive: true, force: true });
await mkdir(outputDirectory, { recursive: true });

for (const example of examples) {
  const categoryTitle = titleCase(example.category.replace(/^\d{2}-/, ""));
  const exportName = pascalCase(example.id);
  const source = `// Generated by scripts/generate-stories.mjs. Do not edit.\n` +
`import type { Meta, StoryObj } from "@storybook/react-vite";\n\n` +
`const exampleBaseUrl = (import.meta.env.VITE_EXAMPLE_BASE_URL ?? "http://localhost:5173").replace(/\\/$/, "");\n\n` +
`function ExampleFrame() {\n` +
`  return (\n` +
`    <iframe\n` +
`      title=${JSON.stringify(example.title)}\n` +
`      src={\`${"${exampleBaseUrl}"}${example.route}\`}\n` +
`      style={{ width: "100%", height: "100vh", border: 0, display: "block" }}\n` +
`      allow="fullscreen"\n` +
`    />\n` +
`  );\n` +
`}\n\n` +
`const meta = {\n` +
`  title: ${JSON.stringify(`Examples/${example.category.slice(0, 2)} ${categoryTitle}`)},\n` +
`  component: ExampleFrame,\n` +
`  parameters: {\n` +
`    docs: { description: { story: ${JSON.stringify(example.description)} } },\n` +
`    tags: ${JSON.stringify(example.tags)}\n` +
`  }\n` +
`} satisfies Meta<typeof ExampleFrame>;\n\n` +
`export default meta;\n` +
`type Story = StoryObj<typeof meta>;\n\n` +
`export const ${exportName}: Story = { name: ${JSON.stringify(example.title)} };\n`;

  await writeFile(resolve(outputDirectory, `${example.id}.stories.tsx`), source, "utf8");
}

console.log(`Generated ${examples.length} Storybook stor${examples.length === 1 ? "y" : "ies"}.`);

function titleCase(value) {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function pascalCase(value) {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}
